<div style="float: right; margin: 0px 15px 15px 0px;">
<img src="https://upload.wikimedia.org/wikipedia/commons/b/b6/HULT_IBS_Logo_Outline_Black_%28cropped%29.png" width=150/>
</div>
<h1> Python for Data Analysis: Methods & Tools </h1>
<em> <strong>Python for everyday people </strong></em>
<br><br>
Written by Felipe Dominguez - Professor Adjunct <br>
Hult International Business School <br>
<br>
<h1><u> Chapter 02 - Data Types - numbers, strings, list, dictionaries, and more!</u></h1>
<em> Exercise workbook - Class 03</em>

<h3>1. Ranges</h3>

<h4>1.1. Create a range from 50 to 150 with steps of 10 (including 150). Then print it as a list.</h4>

In [2]:
# Exervcise 1.1.
# Declare a range data type
my_range = range(50, 151, 10)

# Transform the rango into a list
new_list = list(my_range)

# print the outcome
print(new_list)

[50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]


<h4>1.2. Create a list from 99 to 9 so all numbers are divisible by 3 (Including 9).</h4>

In [4]:
# Exercise 1.3.
# Declare range
my_range = range(99, 8, -3)

# Transform range into list
my_list = list(my_range)

# print outcome
print(my_list)

[99, 96, 93, 90, 87, 84, 81, 78, 75, 72, 69, 66, 63, 60, 57, 54, 51, 48, 45, 42, 39, 36, 33, 30, 27, 24, 21, 18, 15, 12, 9]


<h3>2. Numpy Arrays</h3>

<h4>2.1. Given the following array, complete the tasks a, b, c, and d.</h4>

~~~
np_array = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
~~~

<h5>a. Retrieve the third row of the array</h5>

In [14]:
# Exercise 2.1.a.
import numpy as np

np_array = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(np_array)


print("\nPrinting the 3rd row of the array")
newarray = np_array[2]
print(newarray)

[[11 22 33]
 [44 55 66]
 [77 88 99]]

Printing the 3rd row of the array
[77 88 99]


<h4>b. Retrieve the first element of each row ("column 1")</h4>

In [15]:
# Exercise 2.1.b.
print("\nPrinting the first element of each row.")
newarray = np_array[0]
print(newarray)


Printing the first element of each row.
[11 22 33]


<h4>c. Create a new 9x1 array based on the original 3x3 array</h4>

In [17]:
# Exercise 2.1.c.
new_array = np_array.reshape(9, 1)
print("\nPrinting new 9x1 array")
print(new_array)


Printing new 9x1 array
[[11]
 [22]
 [33]
 [44]
 [55]
 [66]
 [77]
 [88]
 [99]]


<h4>2.2. Create a 5x2 numpy array based on a range between 10 to 60 by 5 steps</h4>


In [22]:
# Exercise 2.2.
# Declare range 
my_range = range(10, 60, 5)

# Create a numpy array based on the range
np_array = np.array(my_range)

# Reshape the array, so it is 5x2
np_array = np_array.reshape(5,2)

#print the result
print(np_array)

[[10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]]


<h4>2.3. Return an array with the items greater than the average</h4>

~~~
np_array = np.array([[45, 4, 25, 2], [9, 4, 11, 34]])
~~~

In [24]:
# Exercise 2.3.
# Declare np array
np_array = np.array([[45, 4, 25, 2], [9, 4, 11, 34]])

# Calculate and store the array average
np_average = np_array.mean()

# Define condition
condition = np_array > np_average

# Apply condition and store it in a new array
newarray = np_array[condition]

# print the outcome
print(f"""
The average of the array is: {np_average}
The numbers greater than the average are:
{newarray}""")


The average of the array is: 16.75
The numbers greater than the average are:
[45 25 34]


<h3>3. Dictionaries</h3>

<h4>3.1. Dictionaries operations</h4><br>
<div align = 'justify'>
You have been given a dictionary with Netflix's movies and its views. Answer the questions a and b based on this dictionary.
</div>

<h5>a. Find the number of views of the movie: "Gaga: Five Foot Two"</h5>

In [26]:
# Exercise 3.1.a
nflx_dic = {'The Debt Collector': 1821195, 'Act of Vengeance': 2804479, 'Paradise Lost': 2195477, "Gerald's Game": 3650626, 'Long Shot': 638440, 'Mak Cun': 1010311, 'Our Souls at Night': 3028705, 'Out of Thin Air': 2681938, "Paul Hollywood's Big Continental Road Trip": 230689, 'Satu Hari': 1012350, 'Monster High: Boo York, Boo York': 1526025, 'Cultivating the Seas: History and Future of the Full-Cycle Cultured Kindai Tuna': 2762103, 'Domino': 872663, 'TUNA GIRL': 2574816, '5CM': 2647713, 'Animal World': 220789, 'Hold the Dark': 2307432, 'Lessons from a School Shooting: Notes from Dunblane': 2419534, 'Made in Mexico': 3653712, 'Single': 239278, 'The 3rd Eye': 196138, 'The Sinking Of Van Der Wijck': 2831856, 'Two Catalonias': 1337119, 'Bobby Sands: 66 Days': 2005623, 'Bard of Blood': 744998, 'Deliha 2': 3638900, 'Dragons: Rescue Riders': 3241239, 'In the Shadow of the Moon': 1213329, 'Skylines': 1840094, 'Sturgill Simpson Presents Sound & Fury': 1915540, 'The Politician': 1019394, 'Weeds on Fire': 2273090, 'Much Loved': 3039852, 'Joseph: King of Dreams': 1734449, 'Malaal': 1926128, 'The Grandmaster': 2549410, 'The Inmate': 130965, 'The Hurricane Heist': 2191538, 'Def Comedy Jam 25': 1392697, 'Restless Creature: Wendy Whelan': 2474412, 'Print the Legend': 548250, 'Birders': 3478883, 'Furie': 2755115, 'Leap!': 1401638, 'Oh! Baby (Malayalam)': 839139, 'Oh! Baby (Tamil)': 2691505, 'USS Indianapolis: Men of Courage': 3286014, 'A Wrinkle in Time': 1258861, 'Teach Us All': 2428947, 'White Island': 1152905, 'Inside Man: Most Wanted': 2812661, 'Jeff Dunham: Beside Himself': 2930368, 'China Salesman': 3377292, 'Swearnet: The Movie': 949689, 'The Bar': 620655, 'Manmadhudu 2': 1842761, 'Team Kaylie': 359856, 'Under the Eiffel Tower': 2298237, 'Audrie & Daisy': 1573055, 'Iliza Shlesinger: Confirmed Kills': 365220, 'BONDING': 1664242, 'Do Paise Ki Dhoop Chaar Aane Ki Baarish': 2770879, '20 Feet From Stardom': 2931730, 'In Darkness': 3248749, 'Gaga: Five Foot Two': 3719550, 'The Bad Batch': 3656264, 'SMOSH: The Movie': 3697506, 'King of Boys': 584112, 'Merry Men: The Real Yoruba Demons': 2035595, "Sarah's Key": 1337902, 'The Wedding Party 2: Destination Dubai': 1471204, 'Vagabond': 1600432, 'Battlefish': 723021, 'DRAGON PILOT: Hisone & Masotan': 602919, 'Hilda': 54948, 'Maniac': 1348196, 'Quincy': 2601704, 'Rafinha Bastos: Ultimatum': 3469996, 'The Good Cop': 2265521, 'Between Two Ferns: The Movie': 3146508, 'Criminal: France': 2021409, 'Criminal: Germany': 658824, 'Criminal: Spain': 3078634, 'Criminal: UK': 2721398, 'Daddy Issues': 2119035, "Inside Bill's Brain: Decoding Bill Gates": 1755104, 'The Hockey Girls': 2000507, 'Travel Mates 2': 707260, 'True: Tricky Treat Day': 3213199, 'Two Sentence Horror Stories': 2438329, 'Mad World': 2281773, 'Mobile Suit Gundam UC': 778879, 'The Bund': 1729892, 'The First Line': 674591, 'Maynard': 84986, 'Monkey Twins': 3277179, 'Bitcoin Heist': 1450158, 'I Am Not Madame Bovary': 2763830, 'Vincent N Roxxy': 1961810, "Chef's Table: France": 2065738}

# input from the user
user_inpu = input(prompt("Select a movie: ")


# retrieve the number of views of Gaga: Five Foot Two
number_views = nflx_dic.get("Gaga: Five Foot Two")
# or
number_views2 = nflix_dic["Gaga: Five Foot Two"]

# print outcome
print(f"""The number of views of Gaga: Five Foot Two is: {number_views}""")

The number of views of Gaga: Five Foot Two is: 3719550


<h5>b. Update the movie Criminal: Germany to Criminal: Chile</h5>

In [ ]:
# Exercise 3.1.b.
# Use the pop method to remove the Criminal: Germany key and store the value removed
value_removed = nflx_dic.pop('Criminal: Germany')

# Create a new key with the value removed
nflx_dic['Criminal: Chile'] = value_removed

# print the result
print('Criminal: Chile:', nflx_dic['Criminal: Chile'])

<h4>3.2. Given the following nested dictionary, obtain Santiago's GMAT score</h4>

~~~
sampleDict = {
    "class": {
        "student": {
                    "name": "Santiago",
                    "exams": {
                                "GMAT": 700,
                                "GRE": 650
            }
        }
    }
}
~~~

In [ ]:
# Exercise 3.2.
# Declare dictionary
student_dic = {
    "class": {
        "student": {
                    "name": "Santiago",
                    "exams": {
                                "GMAT": 700,
                                "GRE": 650
            }
        }
    }
}

# index dictionary until GMTA
student_dic["class"]["student"]["exams"]["GMAT"]

<h4>3.3. Create your own store!</h4><br>
<div align = 'justify'>
Create a program that enables a user to place an order with a business. 
    <ul>
    <li>The program should include a dictionary containing the items available for purchase, with the keys representing the item names and the values representing the prices. </li>
    <li>The program should present the user with a list of items and their corresponding prices, and prompt the user to select the items they wish to purchase.</li>
    <li>Use the cost_of_items function to return the cost of the items selected by the user.</li>
    <li>Print the total sale.</li>
    </ul>
For example:
</div>

    If you are visiting Los Angeles and want to try the famous In-N-Out fast food chain, you can use this program to place an order and see the total cost of your purchase.

In [ ]:
# Start your program here!

menu = {
    "Double Double": 3.95,
    "Double Double Combo": 9.00,
    "cheeseburger": 2.80,
    "cheeseburger combo": 7.55,
    "hamburger": 2.50
}

menu_list = list(menu.items())

user_input = input(f"""
Hello, Werlcome to In-N-Out
What would you like to order?
{menu_list}""").lower()

print(f"""The total cost is: {menu[user_input]}""")